name: 'docker_dart'
description: 'docker_dart library for make your program dart more easy.'
version: '0.0.0'
repository: 'https://github.com/azkadev/docker.git'
issue_tracker: 'https://github.com/azkadev/docker.git'
homepage: 'https://youtube.com/@azkadev'
executables:
  docker_dart: 'docker_dart'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  alfred: '^1.1.1'
  general_universe: '^0.0.0'
  http: '^1.3.0'
  path: '^1.9.0'
  system_information: '^0.0.0'
dev_dependencies:
  lints: '^5.0.0'
  msix: '^3.12.1'
  packagex: '^0.0.0'
  test: 'any'
msix_config:
  display_name: 'docker_dart'
  install_certificate: false
packagex:
  name: 'docker_dart'
  dart_target: 'docker_dart'
  flutter_target: 'main'
  dart_name: 'docker_dart'
  flutter_name: 'docker_dart'
  flutter_commands:
    obfuscate: true
    split-debug-info: '0.0.5'
publish_to: 'none'
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
documentation: 'https://youtube.com/@azkadev'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
