include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
analyzer:
  exclude:
    - test
    - dev
    - templates
  errors:
    unnecessary_brace_in_string_interps: ignore
    unnecessary_string_interpolations: ignore
    todo: ignore
formatter:
  page_width: 9999999999
