name: 'docker_scheme'
description: 'A sample command-line application.'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: null
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
